Repository BC-MAY-21-RN/proyecto-final-m22-pf-t3-reactive-01, pull requests merged in 2022-08, with the labels that each got.

#37 Feature#8 comments
  package-lock.json
  package.json
  src/assets/svg/Animated_Shape.svg
  src/assets/svg/Stacked.js
  src/assets/svg/Stacked_Wave.svg
  src/auth/authFirestore.js
  src/auth/authGoogle.js
  src/auth/cloudFirestore.js
  src/components/atoms/Form/BusyIndicator/Styles.js
  src/components/atoms/Form/BusyIndicator/index.js
  src/components/atoms/Form/Checkbox/Style.js
  src/components/atoms/Form/Checkbox/index.js
  src/components/atoms/Form/CustomButton/Styles.js
  src/components/atoms/Form/CustomButton/index.js
  src/components/atoms/Form/ErrorMessage/Style.js
  src/components/atoms/Form/ErrorMessage/index.js
  src/components/atoms/Form/Input/Style.js
  src/components/atoms/Form/Input/index.js
  src/components/atoms/Header/index.js
  src/components/atoms/Icon/index.js
  src/components/atoms/MenuButtom/butonStyles.js
  src/components/atoms/MenuButtom/index.js
  src/components/atoms/ModalInput/index.js
  src/components/atoms/btnIcon/index.js
  src/components/atoms/register/BusyIndicator/index.js
  src/components/atoms/register/CustomButton/index.js
  src/components/atoms/register/Input/Styles.js
  src/components/atoms/register/Input/index.js
  src/components/atoms/register/checkbox/index.js
  src/navigation/MainStack.js
  src/navigation/MenuStyles.js
  src/screens/Carrito.js
  src/screens/Category.js
  src/screens/Cuenta.js
  src/screens/Home.js
  src/screens/MyProducts.js
  src/screens/ProductDetails.js
  src/screens/Products.js
  src/screens/Register.js
  src/screens/Styles.js
  src/utils/requestCameraPermissions.js
  src/utils/schemasValidateProfile.js
  src/utils/user.js
Labels: ready to merge, Code task, Design task, database, Priority: High

#40 Feature#7 wish list2
  package-lock.json
  package.json
  src/auth/authFirestore.js
  src/auth/cloudFirestore.js
  src/components/atoms/Icon/index.js
  src/components/atoms/ListItem/index.js
  src/components/atoms/VerticalList/index.js
  src/navigation/MainStack.js
  src/screens/Cuenta.js
  src/screens/Favoritos.js
  src/screens/ProductDetails.js
  src/screens/Styles.js
Labels: review required

#41 Feature#8 comments2
  README.md
  package-lock.json
  package.json
  src/auth/authFirestore.js
  src/auth/cloudFirestore.js
  src/components/atoms/Form/Input/Style.js
  src/components/atoms/Form/Input/index.js
  src/components/atoms/ImagePicker/index.js
  src/components/atoms/ListItem/ListItemStyles.js
  src/components/atoms/ListItem/index.js
  src/components/atoms/SellerItem/SellerItemStyles.js
  src/components/atoms/SellerItem/index.js
  src/components/atoms/TextInput/index.js
  src/components/atoms/VerticalList/index.js
  src/screens/Carrito.js
  src/screens/Favoritos.js
  src/screens/Home.js
  src/screens/MyProducts.js
  src/screens/ProductDetails.js
  src/screens/Products.js
  src/screens/Styles.js
Labels: Code task, Design task, database, Priority: High

#45 Feature#43 purchase form
  src/auth/cloudFirestore.js
  src/components/atoms/Icon/index.js
  src/components/atoms/PaymentModal/index.js
  src/components/atoms/PaymentModal/styles.js
  src/components/atoms/TextInput/index.js
  src/components/atoms/btnIcon/index.js
  src/navigation/MainStack.js
  src/screens/ProductDetails.js
  src/screens/Purchase.js
  src/screens/Styles.js
Labels: review required, Priority: Mid

#47 Feature#8 comments3
  package-lock.json
  package.json
  src/auth/cloudFirestore.js
  src/components/atoms/BtnLike/index.js
  src/components/atoms/Form/Input/index.js
  src/components/atoms/ModalOptions/index.js
  src/components/atoms/SellerItem/index.js
  src/navigation/DrawerNavigation.js
  src/navigation/MainStack.js
  src/navigation/MenuStyles.js
  src/screens/Carrito.js
  src/screens/ProductDetails.js
  src/screens/Products.js
  src/screens/Styles.js
  src/utils/cart.js
Labels: Code task, Design task, database, Priority: Mid

#49 Feature#48 show the purchases
  src/auth/authFirestore.js
  src/auth/cloudFirestore.js
  src/components/atoms/BtnCategory/index.js
  src/components/atoms/Item/Styles.js
  src/components/atoms/Item/index.js
  src/components/atoms/ItemAddress/Styles.js
  src/components/atoms/ItemAddress/index.js
  src/components/atoms/ItemCard/Styles.js
  src/components/atoms/ItemCard/index.js
  src/components/atoms/ItemShopping/index.js
  src/components/atoms/ShowMore/Styles.js
  src/components/atoms/ShowMore/index.js
  src/navigation/DrawerNavigation.js
  src/screens/Compras.js
  src/screens/Purchase.js
  src/screens/Styles.js
Labels: review required

#53 Feacture#50 bugs fixes and detail corrections
  package-lock.json
  package.json
  src/auth/authFirestore.js
  src/components/atoms/ButtonToSeller/index.js
  src/components/atoms/ContainerProducts/index.js
  src/components/atoms/ImageAccount/index.js
  src/components/atoms/InputCampAccount/index.js
  src/components/atoms/ModalInput/index.js
  src/components/atoms/ModalRestorePassword/index.js
  src/components/atoms/ModalWarningDelete/index.js
  src/navigation/DrawerNavigation.js
  src/screens/Cuenta.js
  src/screens/ProductsSeller.js
  src/screens/Styles.js
  src/utils/account.js
  src/utils/requestCameraPermissions.js
  src/utils/schemasValidateProfile.js
Labels: review required, Code task, Design task, database
