Repository BC-MAY-21-RN/proyecto-final-m22-pf-t3-reactive-01, pull requests merged in 2022-07, with the labels that each got.

#17 Login and register , busyindicator and Firebase
  .babelrc
  __tests__/App-test.js
  android/app/build.gradle
  android/app/google-services.json
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  package-lock.json
  package.json
  src/auth/authFirestore.js
  src/auth/authGoogle.js
  src/components/atoms/register/BusyIndicator/Styles.js
  src/components/atoms/register/BusyIndicator/index.js
  src/components/atoms/register/CustomButton/Styles.js
  src/components/atoms/register/CustomButton/index.js
  src/components/atoms/register/Input/Styles.js
  src/components/atoms/register/Input/index.js
  src/components/atoms/register/checkbox/Style.js
  src/components/atoms/register/checkbox/index.js
  src/constants/colors.js
  src/screens/Register.js
  src/screens/RegisterStyle.js
Labels: Code task, Design task, database, Priority: High

#18 Feature#3 add products
  android/app/build.gradle
  android/build.gradle
  package-lock.json
  src/auth/authFirestore.js
  src/components/atoms/ListItem/ListItemStyles.js
  src/components/atoms/ListItem/index.js
  src/components/atoms/MenuButtom/index.js
  src/components/atoms/TextInput/index.js
  src/components/atoms/VerticalList/VerticalStyles.js
  src/components/atoms/VerticalList/index.js
  src/components/atoms/register/CustomButton/Styles.js
  src/navigation/MainStack.js
  src/screens/MyProducts.js
  src/screens/Products.js
  src/screens/Register.js
  src/screens/RegisterStyle.js
  src/screens/styles.js
Labels: review required, Code task, Design task, database

#19 Feature#4 Changin the menu style
  src/auth/authFirestore.js
  src/components/atoms/Header/headerStyles.js
  src/components/atoms/Header/index.js
  src/components/atoms/MenuButtom/butonStyles.js
  src/components/atoms/MenuButtom/index.js
  src/navigation/MainStack.js
  src/navigation/MenuStyles.js
  src/screens/Home.js
  src/screens/MyProducts.js
  src/screens/Products.js
  src/screens/styles.js
Labels: review required, Design task

#20 Feature#6 shopping cart
  README.md
  package-lock.json
  package.json
  src/assets/img/shopping-cart.png
  src/auth/authFirestore.js
  src/components/atoms/CounterInput/CounterInputStyles.js
  src/components/atoms/CounterInput/index.js
  src/components/atoms/btnIcon/index.js
  src/components/atoms/register/CustomButton/Styles.js
  src/components/atoms/register/CustomButton/index.js
  src/constants/colors.js
  src/navigation/MainStack.js
  src/screens/Carrito.js
  src/screens/MyProducts.js
  src/screens/Products.js
  src/screens/Register.js
  src/screens/styles.js
  src/utils/cart.js
  src/utils/format.js
Labels: review required, Code task, Design task, database, Priority: High

#24 Feature#4 edit and delete products
  src/auth/authFirestore.js
  src/components/atoms/IconButtom/index.js
  src/components/atoms/ListItem/index.js
  src/components/atoms/SellerItem/SellerItemStyles.js
  src/components/atoms/SellerItem/index.js
  src/components/atoms/VerticalList/VerticalStyles.js
  src/components/atoms/VerticalList/index.js
  src/screens/MyProducts.js
  src/screens/Products.js
Labels: review required, Code task, Design task, database

#25 Feature#21 add image picker
  android/app/src/main/AndroidManifest.xml
  package-lock.json
  package.json
  src/auth/authFirestore.js
  src/components/atoms/ImagePicker/index.js
  src/components/atoms/ImagePicker/pickerStyles.js
  src/components/atoms/SellerItem/index.js
  src/components/atoms/TextInput/index.js
  src/components/atoms/VerticalList/index.js
  src/components/atoms/register/CustomButton/Styles.js
  src/screens/Products.js
  src/screens/styles.js
Labels: ready to merge, review required, Code task, Design task

#26 Feature#22 create screen product details
  .eslintrc.js
  .prettierrc.js
  package-lock.json
  package.json
  src/auth/authFirestore.js
  src/auth/authGoogle.js
  src/components/atoms/Header/headerStyles.js
  src/components/atoms/Header/index.js
  src/components/atoms/ImagePicker/index.js
  src/components/atoms/MenuButtom/butonStyles.js
  src/components/atoms/MenuButtom/index.js
  src/components/atoms/btnIcon/index.js
  src/components/atoms/register/CustomButton/index.js
  src/constants/colors.js
  src/constants/sizes.js
  src/navigation/MainStack.js
  src/navigation/MenuStyles.js
  src/screens/Carrito.js
  src/screens/Compras.js
  src/screens/Cuenta.js
  src/screens/Favoritos.js
  src/screens/Home.js
  src/screens/MyProducts.js
  src/screens/ProductDetails.js
  src/screens/Products.js
  src/screens/Register.js
  src/screens/styles.js
  src/utils/cart.js
Labels: Code task, Design task, database, Priority: High

#28 Feature#27 New feature Icon Cart quantity
  src/components/atoms/Header/headerStyles.js
  src/components/atoms/Header/index.js
  src/constants/colors.js
Labels: Code task, Design task, Priority: Mid

#30 create view profile and use user data
  package-lock.json
  src/assets/img/user.png
  src/screens/Cuenta.js
  src/screens/styles.js
Labels: Code task, Design task

#32 edit info of profile
  package-lock.json
  package.json
  src/auth/authFirestore.js
  src/components/atoms/ModalInput/ModalInputStyle.js
  src/components/atoms/ModalInput/index.js
  src/screens/Cuenta.js
  src/screens/styles.js
  src/utils/schemasValidateProfile.js
Labels: Code task, Design task, database

#35 Feacture#15 delete account
  package-lock.json
  src/auth/authFirestore.js
  src/components/atoms/Loader/LoaderStyle.js
  src/components/atoms/Loader/index.js
  src/components/atoms/ModalInput/ModalInputStyle.js
  src/components/atoms/ModalInput/index.js
  src/components/atoms/ModalWarningDelete/ModalWarningDeleteStyle.js
  src/components/atoms/ModalWarningDelete/index.js
  src/screens/Cuenta.js
  src/screens/styles.js
Labels: Code task, Design task, database
